# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a GPL-3.0
# license that can be found in the LICENSE file.

init:
	mkdir -p logs
	touch logs/traefik.log
	touch logs/access.log
up:
	docker compose up -d
down:
	docker compose down