# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a GPL-3.0
# license that can be found in the LICENSE file.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  changkunResolver:
    acme:
      email: hi@changkun.de
      storage: /etc/traefik/conf/acme.json
      httpChallenge:
        entryPoint: web
  polyredResolver:
    acme:
      email: hi@changkun.de
      storage: /etc/traefik/conf/acme-polyred.json
      httpChallenge:
        entryPoint: web
  golangdesignResolver:
    acme:
      email: hi@changkun.de
      storage: /etc/traefik/conf/acme-golangdesign.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/conf/
    watch: true

api:
  insecure: false
  dashboard: false

ping:
  entryPoint: "traefik"

log:
  filePath: "/logs/traefik.log"
accessLog:
  filePath: "/logs/access.log"
