# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a GPL-3.0
# license that can be found in the LICENSE file.

version: '3'

services:
  www-changkunde:
    image: static:latest
    restart: always
    volumes:
      - /www/changkun.de:/www/changkun.de
    deploy:
      replicas: 1
    environment:
      STATIC_ADDR: :80
      STATIC_FOLDER: /www/changkun.de
      NEWRELIC_NAME: changkun
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
    networks:
      - traefik_proxy
  www-golangdesign:
    image: static:latest
    restart: always
    volumes:
      - /www/golang.design:/www/golang.design
    deploy:
      replicas: 1
    environment:
      STATIC_ADDR: :80
      STATIC_FOLDER: /www/golang.design
      NEWRELIC_NAME: golang-design
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
